### ISSUE TITLE
Non-Int `length` Failure

### ISSUE THREAD

**Issue by Sneagan** [kvannotten/pcd#11]
**Describe the bug**
Feed parser can't handle string values in the `length` property

**To Reproduce**
1. Add [a feed that has string values for `length`](https://theteslashow.com/episodes?format=rss)
3. `pcd sync`
4. `pcd ls`

**Expected behavior**
`length` should be intelligently coerced into a usable format.

I'm happy to help out with this one, but I'd like to know if you're opinionated about an approach. My initial thought is some pre-processor function on the feed before it gets coerced into the `struct`. It looks like this is possible using the [UnmarshalXML method](https://golang.org/src/encoding/xml/read.go?s=7383:7465#L164) on the Unmarshaler type.

**Comment by Sneagan** [comment]
On second thought, is the length even needed?

**Comment by Sneagan** [comment]
I fixed the issue with the `Unmarshaller` type and then immediately ran into missing and `0` value `length` properties in some feeds. I wound up using the `Content-Type` of the response header during the download instead.

**Comment by kvannotten** [comment]
So this was fixed with #12
