### ISSUE TITLE
List Most Recent Episodes of All

### ISSUE THREAD

**Issue by Sneagan** [kvannotten/pcd#15]
**Is your feature request related to a problem? Please describe.**
I'd like to know what the latest episodes of all of the shows are. It might be beyond the scope of this project to manage play status and determine what you haven't heard yet, but you could do that yourself if there is a way to repeatedly list latest.

**Describe the solution you'd like**
A `latest` method seems like the least disruptive way to do this. Maybe with id/name arguments in addition to an `all` or `-1` or something to show a list of the most recent episodes of all shows. Favorites as well? This could be achieved by writing the latest episode name into the show object: `latest_episode_name` or something similar, presumably updated on sync.

**Justification**
If this is beyond the scope of the project this could be accomplished with a separate script, but it seems like a nice feature that would allow users to write more complex interactions. For example, pipe the results of this method into `dmenu` for input, and then pipe the results of `dmenu` back into `pcd` to download the selection(s).

**Comment by Sneagan** [comment]
Or we could get fancy and model it after `ls`:

- `ls -lf` list latest favorites
- `ls -la` list latest all

**Comment by kvannotten** [comment]
I think I would agree with a `pcd ls -all` command or something like that. 

That would just like all episodes with also their ID attached. That way you could use something like this:
` pcd ls all | tac | dmenu | awk '{printf $1" "$2}' | xargs -I % pcd d %`

**Comment by kvannotten** [comment]
> Or we could get fancy and model it after `ls`:
> 
>     * `ls -lf` list latest favorites
> 
>     * `ls -la` list latest all

ye, something along those lines would be nice

**Comment by kvannotten** [comment]
Alright, I've added a preliminary version of this feature. This allows you to do something like this: `pcd ls -a | tac | dmenu | awk -F';' '{printf $1" "$2}' | xargs pcd d` to  spawn a dmenu that allows you to select which one you want to download. It can most likely still be refined, but as a first version it should be alright!
