### ISSUE TITLE
Help message is misleading

### ISSUE THREAD

**Issue by gcantieni** [kvannotten/pcd#19]
**Describe the bug**
The help message claims the config is stored under .config/pcd but it actually checks .config/pcd.yml.

**To Reproduce**
Add file to .config/pcd and sync (nothing happens for me at least). Then try renaming to pcd.yml, this works. Note that the help message says
```
Just add the necessary configuration under ~/.config/pcd and you can get started.
...
Flags:
      --config string   config file (default is $HOME/.config/pcd)
```

**Expected behavior**
Help message should say:
```
Just add the necessary configuration under ~/.config/pcd.yml and you can get started.
...
Flags:
      --config string   config file (default is $HOME/.config/pcd.yml)
```

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Comment by kvannotten** [comment]
Hey,

Thanks for the report! 

I looked around and I think that should have been fixed in 0c51783ebfbc30dfc9e0b8c4e2a80163fe34e454 

Are you using the version from the AUR or from github?

**Comment by gcantieni** [comment]
Ah I'm using the AUR version so that's probably why!

**Comment by gcantieni** [comment]
Yep just cloned and got it running and it's fixed, closing.
