### ISSUE TITLE
Standardize download filenames

### ISSUE THREAD

**Issue by ShadiZade** [kvannotten/pcd#27]
When downloading episodes, the naming schemes are different between podcasts (for example, one podcast I follow names every episode 'stream.mp4', creating file conflicts). Since pcd fetches the episode name from the feed, wouldn't it be more convenient for the file to be automatically named? Castget does this by allowing filename patterns in the config file (e.g. `filename=%(date)-%(title)`).

Info:
pcd v 0.7

**Comment by ShadiZade** [comment]
Thank you for your response! I'll be waiting for the new release, and that will be goodbye to Kasts and Castget for me. I really found that pcd fits my workflow to a T, except for this one small gripe.

**Comment by kvannotten** [comment]
It should be addressed in the latest version on master branch.

**Comment by ShadiZade** [comment]
@kvannotten Wonderful! Thank you so much. Not to be too much of a bother, but wouldn't the number of the episode (as shown in the ls command) be a good option to add to `filenameTemplate`, especially for sorting purposes? As you said in the docs, date formats differ.

**Comment by kvannotten** [comment]
I have added the ID. But be aware that this is a generated ID. It's also relative. That means that when the owner of the podcast removes previous episodes, the ids will shift.

**Comment by ShadiZade** [comment]
@kvannotten My sincere thanks. Sorry if I bothered you!

**Comment by ShadiZade** [comment]
@kvannotten Bug report on this one: download will immediately fail if the title has a `/` in it. Messes with the file system. Also, HTML codes like `&amp;` and `&#34;` will not render. Example: "`What is sugar? 'Added' sugar? 'Natural' sugar?`" will download into "`What is sugar? &#39;Added&#39; sugar? &#39;Natural&#39; sugar?.mp3`"

**Comment by kvannotten** [comment]
Indeed, it's the go templating engine that automatically escapes HTML strings. I have made a change that will rectify both issues.

**Comment by ShadiZade** [comment]
Works like a charm!
