### ISSUE TITLE
Configuration example on README has 2 spaces in the begging of every line

### ISSUE THREAD

**Issue by evertonstz** [kvannotten/pcd#6]
Don't know if it's intended behavior, but copying and pasting that template didn't work for me because of the spaces as pcd was unable to load the file (it didn't show any error, it just didn't synced), after removing the spaces pcd recognized the file and synced normally.

**Comment by kvannotten** [comment]
Updated the Readme but still have to test if my change worked. I will also make an issue to improve error reporting for this problem.

**Comment by kvannotten** [comment]
Seems to work for me now!
