### ISSUE TITLE
File names are messed up even after the download ends

### ISSUE THREAD

**Issue by evertonstz** [kvannotten/pcd#9]
**Describe the bug**
Downloading any podcast will result in a file with a name that instead of ending with ".mp3" will end with ".mp3?dest-id=(some number here)" messing with the extension name ends with the audio file being unplayable by some music players.

here's a "ls -la" of one of my download folders:

`-rw-r--r-- 1 peep peep 90943970 fev 27 18:31 'LPOTL353REDOFINAL.mp3?dest-id=754182'`
`-rw-r--r-- 1 peep peep 66852854 fev 27 18:23 'SideStoriesDOATTEND_Final.mp3dest-id=754182'`
 

**To Reproduce**
1. download any episode of any podcast using pcd
2. use any file manager or terminal to check the downloaded file
4. See error in the filename

**Expected behavior**
A file with a clean ".mp3" extension

**Desktop (please complete the following information):**
 - OS: Manjaro Linux x86_64 
 - Version: v0.6.0-1 (built from AUR)

**Comment by kvannotten** [comment]
That's indeed annoying. Will fix!
